### ISSUE TITLE
Example code compiles, but doesn't run.

### ISSUE THREAD

**Issue by Raffo** [mikkeloscar/gin-swagger#2]
Maybe I did it wrong... 

```
cd example
go build . 
./example --insecure-http
panic: handlers are already registered for path ''/healthz'

goroutine 1 [running]:
github.com/gin-gonic/gin.(*node).addRoute(0xc4201e52c0, 0xc4204ef1d0, 0x8, 0xc42032b340, 0x3, 0x3)
	/Users/raffo/Development/go/src/github.com/gin-gonic/gin/tree.go:235 +0xa9b
github.com/gin-gonic/gin.(*Engine).addRoute(0xc42026f440, 0x17859b6, 0x3, 0xc4204ef1d0, 0x8, 0xc42032b340, 0x3, 0x3)
	/Users/raffo/Development/go/src/github.com/gin-gonic/gin/gin.go:237 +0x1bc
github.com/gin-gonic/gin.(*RouterGroup).handle(0xc42026f440, 0x17859b6, 0x3, 0x1789ace, 0x8, 0xc4201d4960, 0x1, 0x1, 0xc420130d01, 0xc4201d4960)
	/Users/raffo/Development/go/src/github.com/gin-gonic/gin/routergroup.go:71 +0xe7
github.com/gin-gonic/gin.(*RouterGroup).GET(0xc42026f440, 0x1789ace, 0x8, 0xc4201d4960, 0x1, 0x1, 0xc420551f10, 0x1048a71)
	/Users/raffo/Development/go/src/github.com/gin-gonic/gin/routergroup.go:99 +0x7c
github.com/mikkeloscar/gin-swagger/example/restapi.NewAPI(0x1aef580, 0xc4204ef0e1, 0x1b37600, 0xc420376000)
	/Users/raffo/Development/go/src/github.com/mikkeloscar/gin-swagger/example/restapi/api.go:456 +0x280
main.main()
	/Users/raffo/Development/go/src/github.com/mikkeloscar/gin-swagger/example/main.go:19 +0xae
```

**Comment by mikkeloscar** [comment]
Fixed in 500cd8764c6c7379a2331f1f0e175ea699f135b3

I removed the need for defining a `/healthz` endpoint in the swagger spec, but forgot to actually remove it from the example.

`/healthz` is automatically provided by gin-swagger.
