### ISSUE TITLE
Does not work with go1.13

### ISSUE THREAD

**Issue by mikkeloscar** [mikkeloscar/gin-swagger#38]
When building with go1.13 the code generation fails with the following error:

```
./build/gin-swagger -A cluster-registry -f swagger.yaml
2019/09/04 10:10:14 validating spec /workspace/swagger.yaml
panic: Invalid schema provided to SchemaValidator: object has no key "default"
goroutine 1 [running]:
github.com/go-openapi/validate.NewSchemaValidator(0xc000908d80, 0xb38f80, 0xc000908d80, 0x0, 0x0, 0xc9ba20, 0xc000390660, 0xc000bc8280)
	/go/pkg/mod/github.com/go-openapi/validate@v0.17.0/schema.go:71 +0xf83
github.com/go-openapi/validate.(*SpecValidator).Validate(0xc00063c900, 0xafe500, 0xc0000aba90, 0xc000bd0000, 0xc000bd00b0)
	/go/pkg/mod/github.com/go-openapi/validate@v0.17.0/spec.go:92 +0x208
github.com/go-openapi/validate.Spec(0xc0000aba90, 0xc9ba20, 0xc000390660, 0x14, 0xbf54014182793a94)
	/go/pkg/mod/github.com/go-openapi/validate@v0.17.0/spec.go:47 +0xad
github.com/go-swagger/go-swagger/generator.validateSpec(0xc00033e740, 0x17, 0xc0000aba90, 0x1, 0x1)
	/go/pkg/mod/github.com/go-swagger/go-swagger@v0.17.1-0.20181009150033-e06c79d1fcd4/generator/shared.go:882 +0x89
github.com/go-swagger/go-swagger/generator.validateAndFlattenSpec(0xc00016e600, 0xc0000aba90, 0xc00033e740, 0x17, 0xc0000aba90)
	/go/pkg/mod/github.com/go-swagger/go-swagger@v0.17.1-0.20181009150033-e06c79d1fcd4/generator/shared.go:1055 +0x42e
github.com/go-swagger/go-swagger/generator.newAppGenerator(0x7fff9e029a98, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00016e600, 0x9d7918, ...)
	/go/pkg/mod/github.com/go-swagger/go-swagger@v0.17.1-0.20181009150033-e06c79d1fcd4/generator/support.go:92 +0x15c
github.com/go-swagger/go-swagger/generator.GenerateServer(0x7fff9e029a98, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00016e600, 0x0, ...)
	/go/pkg/mod/github.com/go-swagger/go-swagger@v0.17.1-0.20181009150033-e06c79d1fcd4/generator/support.go:39 +0x94
main.run(0x7fff9e029a98, 0x10, 0x7fff9e029aac, 0xc, 0xc00008f100, 0xc0002bc570)
	/go/pkg/mod/github.com/mikkeloscar/gin-swagger@v0.0.0-20181114131215-6cf5854275b5/main.go:144 +0x5b0
main.main()
	/go/pkg/mod/github.com/mikkeloscar/gin-swagger@v0.0.0-20181114131215-6cf5854275b5/main.go:34 +0x35b
Makefile:30: recipe for target 'generate' failed
make: *** [generate] Error 2
Step finished unsuccessfully.
```

It's not clear what is the issue but it works with `go1.12`. I suspect it's something inside `reflect` package that changed because of where it's crashing.

**Comment by mikkeloscar** [comment]
I could replicate this issue with plain go-swagger: https://github.com/go-swagger/go-swagger/issues/2058 so it's an upstream issue.
